### PR TITLE
Add table node

### PR DESCRIPTION
**Pull request by kazuhitoyokoi**
I created the table node which I previously suggested on the following slide.
https://github.com/node-red-hitachi/node-red-notes/blob/master/Teleconference/20190604/20190604nodered_teleconference_yokoi.pptx

### CODE REVIEW

**Comment by kazuhitoyokoi** [comment]
@dceejay Thank you! I'm going to publish it on npm after my vacation (in the week of 2nd September).

**Comment by dceejay** [comment]
I can do that for you from here if you like

**Comment by kazuhitoyokoi** [comment]
@dceejay Thank for your kindness! (I am already on my way to vacation🏖) Could you publish it on npm?

**Comment by dceejay** [comment]
ok done - if you tell me (privately via slack) the email you use on npm I can add you as owner so you can update as required also.

**Pull request merged**
