### PR TITLE
Example for ui-tablewith ui_control

### PR DESCRIPTION
**Pull request by Christian-Me**
hope this is "readable" and "understandable" (sorry I`m not a native speaker) and the example works

### CODE REVIEW

**Comment by dceejay** [comment]
Looks great.

**Comment by Christian-Me** [comment]
Let`s see if it is useful for others too. Thank you for all your help and time.
As this is my first "major" commitment, should I write a little post in the "dashboard" section of the forum or let it sit there for a wile until somebody finds out?

**Second question**: How I should proceed with the next task: add/delete/update single table lines to avoid sending the hole table for each update of a value.

 I'm planning to use the updateData, addData, replaceData and perhaps others [as described here](http://tabulator.info/docs/4.4/update). Also I like to use the table for value entry like clicking on icons or even entering values. In my case set temperatures or change modes for the room thermostats.

As mentioned before I plan to do this via ui_control not to break the current payload/topic message syntax even if the ui_control object is (as I see it) initially designed for modifying the appearance of a dashboard element and not the content. Or is it better to define msg.payload.updateData / msg.payload.addData and so on which also should not break current implementation of the table note.

Last but not least I like to add a topic field to this node as in my configuration / flows all emitting nodes should send a msg.topic sting to determine the origin of the payload further down the flow.

**Comment by dceejay** [comment]
Hi - sure feel free to talk about it... it's good stuff.
Other questions - hmm - that will need thought... yes it shouldn't use ui_control as that is indeed supposed to be about appearance rather than data - and generally causes a redraw of the widget etc.

I would also ty to avoid topic. Currently the node expects only a payload of an array - of data. - It could also accept an object - which could then contain the extra command and data - or could use a higher level property msg.table_command   etc... 

The node does send a msg.topic containing the cell name when you click on a cell. and the payload contains the whole row - eg.
```
{"topic":"Age","payload":{"Name":"Kazuhito Yokoi","Age":"35","Favourite Color":"red","Date Of Birth":"12/09/1983"},"row":0,"socketid":"FE6euAEfqN-0v5vPAAAA","_msgid":"f5c41a58.1bf798"}
```

**Comment by Christian-Me** [comment]
Good Morning.
fine, hope I‘ll find some time to do that.
I forgot that there was an issue with msg.topic. In an early version I implemented a topic field in the config form to find out that it is already used by the “onClick” function.
Perhaps I should do some tests first to find out what is necessary. Best will be to check if msg.payload is an array = full table or an object {command:”aCommand”, arguments; [commandArguments]} which than trigger some or perhaps all available tabulator functions.
Let’s see.
This will take a wile because of so many other “building sites” open.
Regards Chris.

**Pull request merged**
