### PR TITLE
Fix merging column definitions with nested (grouped) columns

### PR DESCRIPTION
**Pull request by Christian-Me**
Hi,

just a little fix addressing this bug: https://discourse.nodered.org/t/ui-table-supports-ui-control/18870/34?u=christian-me

If we use ui_control to merge new column definition nested (grouped) columns all went inside the first group (because these column objects have no field property = undefined)

Should be fixed:
image

### CODE REVIEW

**Comment by Christian-Me** [comment]
That was fast, thank you!

**Comment by Christian-Me** [comment]
Just found the issue regarding the same problem and noticed I haven't changed the version from 0.3.4 to 0.3.5 (or do you count only equal numbers). Should I have done that? Or does this not cause problems. Still not familiar with github and npm.

**Comment by dceejay** [comment]
happy either way. Are you happy to publish as-is now - or more changes to come soon ?

**Comment by Christian-Me** [comment]
Nope ... think / hope the bug is fixed. Works with my tables

**Comment by dceejay** [comment]
All done - many thanks as always !

**Pull request merged**
